### ISSUE TITLE
Can I fine tune the Yi-34B model with 8 3090ti(24G)

### ISSUE THREAD

**Issue by jiqizaisikao** [01-ai/Yi#149]
There is no channel to get a100 now , thanks

**Comment by shiyue-loop** [comment]
I think [PEFT](https://github.com/huggingface/peft) (Parameter-Efficient Fine-Tuning) methods may help you.

**Comment by jiqizaisikao** [comment]
Yes , i will use lora as PEFT ,is it ok for lora

**Comment by shiyue-loop** [comment]
@jiqizaisikao Also, other cool memory-saving tricks, like [parallelism](https://huggingface.co/docs/transformers/v4.15.0/parallelism) (since you mentioned having 8 GPUs) and [CPU offloading](https://www.deepspeed.ai/tutorials/zero-offload/#zero-offload-overview), might really come in handy too.

**Comment by shiyue-loop** [comment]
> is it ok for lora

Yes, using lora is a good choice

**Comment by jiqizaisikao** [comment]
I tried to fine tune Yi-6B
 bash run_sft_lora_Yi_6b.sh  with batch size=1
on  computer with two 4090 gpus
but torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 1; 23.65 GiB total capacity; 21.23 GiB already allocated; 66.06 MiB free; 23.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by jiangchengSilent** [comment]
> I tried to fine tune Yi-6B bash run_sft_lora_Yi_6b.sh with batch size=1 on computer with two 4090 gpus but torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 1; 23.65 GiB total capacity; 21.23 GiB already allocated; 66.06 MiB free; 23.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

In zero2+offload setting, lora doesn't actually save GPU memory. That is because the states and gradients in optimize save by lora, are in CPU by offload. Since the total num of params increased, the GPU mem takes a littlte bit more.

Also, since the number of GPUs is small (ie 2), zero technique may have little effect in GPU mem reduction.

You may consider to reduce the max_seq_len to a very small number (ie 128) then increase gradually to find the limit of your hardware.
